$pdf_mode = 1;
$preview_continuous_mode = 1;
$silent = 1;
$sleep_time = 1;

$pdf_previewer = "open -a Skim";
$pdflatex = 'pdflatex -synctex=1 -interaction=nonstopmode';
@generated_exts = (@generated_exts, 'synctex.gz');

@default_files = ('main.tex');
